spring:
  application:
    name: server
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 25

python:
  server:
    base-url: ${PYTHON_SERVER_URL:http://127.0.0.1:8000}
    timeout:
      connect: 10000   # 10초
      response: 600000  # 600초 (10분 - LLM 처리 + Whisper STT 시간 고려)

jwt:
  secret: ${JWT_SECRET:change-this-to-a-very-long-secret-key-at-least-32-bytes!}
  issuer: "archiveat"
  access-token-expiration-ms: 3600000  # 1시간
  refresh-token-expiration-ms: 1209600000   #14일

springdoc:
  # 1. 화면(UI) 접속 주소 변경
  swagger-ui:
    path: /archiveat-docs  #localhost:8080/archiveat-docs로 접속

    doc-expansion: none    # none: 다 접힘(깔끔), list: 다 펼침(기본값)

